version: 2
updates:
  # JavaScript/npm paketleri için ayarlar (Frontend)
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    # Tüm npm güncellemelerini tek bir PR'da topla
    groups:
      npm-dependencies:
        patterns:
          - "*"
    # Güvenlik güncellemelerini hemen yap
    open-pull-requests-limit: 10
    reviewers:
      - "sarperhorata"
    assignees:
      - "sarperhorata"
    commit-message:
      prefix: "chore"
      include: "scope"

  # Python/pip paketleri için ayarlar (Backend)
  - package-ecosystem: "pip"
    directory: "/backend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    # Tüm pip güncellemelerini tek bir PR'da topla
    groups:
      pip-dependencies:
        patterns:
          - "*"
    # Güvenlik güncellemelerini hemen yap
    open-pull-requests-limit: 10
    reviewers:
      - "sarperhorata"
    assignees:
      - "sarperhorata"
    commit-message:
      prefix: "chore"
      include: "scope"

  # GitHub Actions için ayarlar
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    # GitHub Actions güncellemelerini grupla
    groups:
      github-actions:
        patterns:
          - "*"
    open-pull-requests-limit: 5
    reviewers:
      - "sarperhorata"
    assignees:
      - "sarperhorata"
    commit-message:
      prefix: "ci"
      include: "scope"

  # Docker için ayarlar (eğer varsa)
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    groups:
      docker-dependencies:
        patterns:
          - "*"
    open-pull-requests-limit: 5
    reviewers:
      - "sarperhorata"
    assignees:
      - "sarperhorata"
    commit-message:
      prefix: "chore"
      include: "scope" 