version: 2
updates:
  # JavaScript/npm paketleri için ayarlar (Frontend)
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    # Güvenlik güncellemelerini hemen yap
    open-pull-requests-limit: 5
    reviewers:
      - "sarperhorata"
    assignees:
      - "sarperhorata"
    commit-message:
      prefix: "chore"
      include: "scope"
    # Güvenlik güncellemelerini otomatik merge et
    allow:
      - dependency-type: "direct"
    # Güvenlik güncellemelerini otomatik merge et
    automerge: true
    # Major version güncellemelerini manuel onay için bırak
    ignore:
      - dependency-name: "react"
        update-types: ["version-update:semver-major"]
      - dependency-name: "react-dom"
        update-types: ["version-update:semver-major"]
      - dependency-name: "typescript"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@mui/material"
        update-types: ["version-update:semver-major"]
      - dependency-name: "react-router-dom"
        update-types: ["version-update:semver-major"]
      - dependency-name: "firebase"
        update-types: ["version-update:semver-major"]
    # Güvenlik güncellemelerini grupla
    groups:
      security-updates:
        patterns:
          - "*"
        update-types:
          - "security"
      minor-patch-updates:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
        exclude-patterns:
          - "react"
          - "react-dom"
          - "typescript"
          - "@mui/material"
          - "react-router-dom"
          - "firebase"

  # Python/pip paketleri için ayarlar (Backend)
  - package-ecosystem: "pip"
    directory: "/backend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    # Güvenlik güncellemelerini hemen yap
    open-pull-requests-limit: 5
    reviewers:
      - "sarperhorata"
    assignees:
      - "sarperhorata"
    commit-message:
      prefix: "chore"
      include: "scope"
    # Güvenlik güncellemelerini otomatik merge et
    allow:
      - dependency-type: "direct"
    # Güvenlik güncellemelerini otomatik merge et
    automerge: true
    # Major version güncellemelerini manuel onay için bırak
    ignore:
      - dependency-name: "fastapi"
        update-types: ["version-update:semver-major"]
      - dependency-name: "pydantic"
        update-types: ["version-update:semver-major"]
      - dependency-name: "beanie"
        update-types: ["version-update:semver-major"]
      - dependency-name: "marshmallow"
        update-types: ["version-update:semver-major"]
      - dependency-name: "sqlalchemy"
        update-types: ["version-update:semver-major"]
    # Güvenlik güncellemelerini grupla
    groups:
      security-updates:
        patterns:
          - "*"
        update-types:
          - "security"
      minor-patch-updates:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
        exclude-patterns:
          - "fastapi"
          - "pydantic"
          - "beanie"
          - "marshmallow"
          - "sqlalchemy"

  # GitHub Actions için ayarlar
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    # GitHub Actions güncellemelerini grupla
    groups:
      github-actions:
        patterns:
          - "*"
    open-pull-requests-limit: 3
    reviewers:
      - "sarperhorata"
    assignees:
      - "sarperhorata"
    commit-message:
      prefix: "ci"
      include: "scope"
    # Güvenlik güncellemelerini otomatik merge et
    automerge: true

  # Docker için ayarlar (eğer varsa)
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    groups:
      docker-dependencies:
        patterns:
          - "*"
    open-pull-requests-limit: 3
    reviewers:
      - "sarperhorata"
    assignees:
      - "sarperhorata"
    commit-message:
      prefix: "chore"
      include: "scope"
    # Güvenlik güncellemelerini otomatik merge et
    automerge: true 