services:
  # Backend API Service
  - type: web
    name: remote-jobs-api
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.12
      - key: API_HOST
        value: 0.0.0.0
      - key: API_DEBUG
        value: false
      - key: API_RELOAD
        value: false
      - key: CORS_ORIGINS
        value: https://remote-jobs-site.onrender.com,https://remote-jobs.netlify.app
      - key: CORS_ALLOW_CREDENTIALS
        value: true
      # Email settings
      - key: EMAIL_HOST
        sync: false
      - key: EMAIL_PORT
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASSWORD
        sync: false
      - key: EMAIL_FROM
        sync: false
      # Telegram settings
      - key: TELEGRAM_BOT_TOKEN
        sync: false

databases:
  # Database
  - name: remote-jobs-db
    databaseName: remote_jobs
    user: remote_jobs_admin
    plan: free

## Add the following environment variables in Render dashboard:
# EMAIL_HOST=smtp.gmail.com
# EMAIL_PORT=587
# EMAIL_USER=your-email@gmail.com
# EMAIL_PASSWORD=your-app-password
# EMAIL_FROM=your-email@gmail.com
# TELEGRAM_BOT_TOKEN=your-telegram-bot-token

services:
  - type: web
    name: remote-jobs-monitor-backend
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: remote-jobs-monitor-db
          property: connectionString
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 30

databases:
  - name: remote-jobs-monitor-db
    databaseName: remote_jobs_monitor
    user: remote_jobs_monitor
    plan: free

services:
  - type: web
    name: buzz2remote-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: MONGODB_URL
        value: mongodb://localhost:27017/buzz2remote
      - key: SECRET_KEY
        generateValue: true
      - key: OPENAI_API_KEY
        sync: false
      - key: DOMAIN
        value: buzz2remote.com
      - key: CORS_ORIGINS
        value: https://buzz2remote.com,https://www.buzz2remote.com
    healthCheckPath: /admin/dashboard
    plan: starter
    autoDeploy: true
    branch: main
    numInstances: 1
    disk:
      name: tmp
      mountPath: /tmp
      sizeGB: 1
    env:
      - key: NODE_ENV
        value: production
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: X-XSS-Protection
        value: 1; mode=block
      - path: /*
        name: Strict-Transport-Security
        value: max-age=31536000; includeSubDomains 