services:
  # Backend API Service
  - type: web
    name: remote-jobs-api
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.12
      - key: API_HOST
        value: 0.0.0.0
      - key: API_DEBUG
        value: false
      - key: API_RELOAD
        value: false
      - key: CORS_ORIGINS
        value: https://remote-jobs-site.onrender.com,https://remote-jobs.netlify.app
      - key: CORS_ALLOW_CREDENTIALS
        value: true
      # Email settings
      - key: EMAIL_HOST
        sync: false
      - key: EMAIL_PORT
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASSWORD
        sync: false
      - key: EMAIL_FROM
        sync: false
      # Telegram settings
      - key: TELEGRAM_BOT_TOKEN
        sync: false

databases:
  # Database
  - name: remote-jobs-db
    databaseName: remote_jobs
    user: remote_jobs_admin
    plan: free

## Add the following environment variables in Render dashboard:
# EMAIL_HOST=smtp.gmail.com
# EMAIL_PORT=587
# EMAIL_USER=your-email@gmail.com
# EMAIL_PASSWORD=your-app-password
# EMAIL_FROM=your-email@gmail.com
# TELEGRAM_BOT_TOKEN=your-telegram-bot-token

services:
  - type: web
    name: remote-jobs-monitor-backend
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: remote-jobs-monitor-db
          property: connectionString
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 30

databases:
  - name: remote-jobs-monitor-db
    databaseName: remote_jobs_monitor
    user: remote_jobs_monitor
    plan: free 