security:
  ignore-vulnerabilities:
    # All critical vulnerabilities have been fixed:
    # - ecdsa (CVE-2024-23342) -> Replaced with cryptography library
    # - python-jose (CVE-2024-33663, CVE-2024-33664) -> Replaced with PyJWT
    # - pypdf2 (CVE-2023-36464) -> Replaced with pypdf
    
    # Only keep non-critical vulnerabilities that don't affect our use case
    # No vulnerabilities to ignore currently

  # Only report high and critical vulnerabilities
  ignore-cvss-severity-below: 7.0

  # Continue even if vulnerabilities are found
  continue-on-vulnerability-error: true 