services:
  - type: web
    name: buzz2remote-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.12
      - key: DATABASE_URL
        fromDatabase:
          name: buzz2remote-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ENVIRONMENT
        value: production
      - key: CORS_ORIGINS
        value: "https://buzz2remote.netlify.app,https://buzz2remote-frontend.netlify.app"
      
      # Database Configuration
      - key: MONGODB_URI
        sync: false
      - key: MONGODB_DB_NAME
        value: buzz2remote
      
      # Security
      - key: JWT_SECRET_KEY
        sync: false
      
      # OpenAI Integration for Enhanced CV Parsing
      - key: OPENAI_API_KEY
        sync: false
      
      # LinkedIn OAuth (Optional)
      - key: LINKEDIN_CLIENT_ID
        sync: false
      - key: LINKEDIN_CLIENT_SECRET
        sync: false
      
      # Job API Keys (Optional)
      - key: JSEARCH_API_KEY
        sync: false
      - key: REED_API_KEY
        sync: false
      - key: ADZUNA_APP_ID
        sync: false
      - key: ADZUNA_APP_KEY
        sync: false
      - key: JOBS2CAREERS_PUBLISHER_ID
        sync: false
      
      # Email Configuration
      - key: EMAIL_HOST
        sync: false
      - key: EMAIL_PORT
        sync: false
      - key: EMAIL_USERNAME
        sync: false
      - key: EMAIL_PASSWORD
        sync: false
      - key: EMAIL_FROM
        sync: false
      
      # Telegram Bot
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHANNEL_ID
        sync: false
      
      # URLs
      - key: RENDER_URL
        value: https://buzz2remote-api.onrender.com
      - key: FRONTEND_URL
        value: https://buzz2remote.netlify.app
      - key: ALLOWED_ORIGINS
        value: https://buzz2remote.netlify.app,http://localhost:3000 