services:
  - type: web
    name: remote-jobs-api
    env: python
    buildCommand: ./build.sh
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: EMAIL_HOST
        sync: false
      - key: EMAIL_PORT
        sync: false
      - key: EMAIL_USERNAME
        sync: false
      - key: EMAIL_PASSWORD
        sync: false
      - key: EMAIL_FROM
        sync: false
      - key: GOOGLE_SHEETS_SPREADSHEET_ID
        sync: false
      - key: GOOGLE_SHEETS_TOKEN
        sync: false
      - key: GOOGLE_SHEETS_REFRESH_TOKEN
        sync: false
      - key: GOOGLE_SHEETS_CLIENT_ID
        sync: false
      - key: GOOGLE_SHEETS_CLIENT_SECRET
        sync: false
      - key: RENDER_URL
        value: https://remote-jobs-62gn.onrender.com
      - key: FRONTEND_URL
        value: https://remote-jobs.netlify.app
      - key: ALLOWED_ORIGINS
        value: https://remote-jobs.netlify.app 