[build]
  base = "frontend"
  publish = "build"
  command = "npm install && CI=false npm run build"

[build.environment]
  NODE_VERSION = "18"
  REACT_APP_API_URL = "https://buzz2remote-api.onrender.com"
  REACT_APP_ENVIRONMENT = "production"
  CI = "false"
  NPM_FLAGS = "--legacy-peer-deps"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable" 