name: Deploy Backend

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
      - '.github/workflows/deploy.yml'
  workflow_run:
    workflows: ["Backend Tests"]
    types:
      - completed
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: []
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        cd backend
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run pre-deployment tests
      run: |
        cd backend
        python -m pytest tests/test_sanity.py -v --timeout=10
      env:
        TESTING: true
        MONGODB_URI: mongodb://localhost:27017
        DATABASE_NAME: test_buzz2remote
    
    - name: Deploy to staging (if develop branch)
      if: github.ref == 'refs/heads/develop'
      run: |
        echo "Deploying to staging environment..."
        # Add your staging deployment commands here
        # Example: docker build, docker push, kubectl apply, etc.
    
    - name: Deploy to production (if main branch)
      if: github.ref == 'refs/heads/main'
      run: |
        echo "Deploying to production environment..."
        # Add your production deployment commands here
        # Example: docker build, docker push, kubectl apply, etc.
    
    - name: Health check
      run: |
        echo "Running health checks..."
        # Add health check commands here
        # Example: curl endpoints, check database connectivity, etc.
    
    - name: Notify deployment status
      run: |
        echo "Deployment completed successfully!"
        # Add notification commands here (Slack, Discord, etc.) 