name: Deploy to Render

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy Backend to Render
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Render
        run: |
          if [ "${{ secrets.RENDER_DEPLOY_HOOK_URL }}" ]; then
            curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK_URL }}"
          else
            echo "RENDER_DEPLOY_HOOK_URL secret not set"
          fi 