name: Security Audit

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  schedule:
    # Run security audit daily at 2 AM UTC
    - cron: '0 2 * * *'

jobs:
  python-security:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install safety bandit
        cd backend && pip install -r requirements.txt
    
    - name: Run Safety (Python dependency security)
      run: |
        cd backend
        # Use modern scan command instead of deprecated check
        safety scan --output json --save-json safety-report.json || echo "Safety scan completed with findings"
        safety scan || echo "Safety scan completed"
    
    - name: Run Bandit (Python code security)
      run: |
        cd backend
        bandit -r . -f json -o bandit-report.json --exclude ./venv,./tests,./backup_tests || echo "Bandit scan completed with findings"
        bandit -r . --exclude ./venv,./tests,./backup_tests || echo "Bandit scan completed"
    
    - name: Upload security reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: python-security-reports
        path: |
          backend/safety-report.json
          backend/bandit-report.json

  npm-security:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
    
    - name: Install dependencies
      run: |
        cd frontend
        npm ci --no-optional
    
    - name: Run npm audit
      run: |
        cd frontend
        npm audit --audit-level=moderate --json > npm-audit-report.json || echo "NPM audit completed with findings"
        npm audit --audit-level=moderate || echo "NPM audit completed"
    
    - name: Upload npm audit report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: npm-security-reports
        path: frontend/npm-audit-report.json
